### ISSUE TITLE
ERROR: Unable to open digitizer

### ISSUE THREAD

**Issue by francescopiscitelli** [tblum/jadaq#11]
Sometimes the acq starts and does not find a digitiser, it is random. 
Data with ID Starting run xxxxx is in /data/test23FP_nightwithscript/
Config file is in .../jadaq/config/config2digit_STF_FP2307.ini or here  [config2digit_STF_FP2307.ini.txt](https://github.com/ess-dmsc/jadaq/files/2223958/config2digit_STF_FP2307.ini.txt)
HV on detector 1300V with Co-60 source

It is most often the VX1740D_2 ( VX1740D_31) that fails.

Sometimes there is only one run that fails but sometimes the digit gets stuck and  I need to power cycle the crate to make the digitiser alive again.

Eg. file run 00510 is fine, run 00511 digit 31 failed, run 00512 fine again without power cycle 

MESSAGE:
Setup 2 digitizer(s):
	VX1740D_34
	VX1740D_31
Starting run 00510 (ID 49e300b1cc78f445) 
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 15.001 seconds.
Collecting 55683 events.
Resulting in a collection rate of 3.71195 kHz.

**ERROR: Unable to open digitizer [VX1740D_2]**
Setup 1 digitizer(s):
	VX1740D_34
Starting run 00511 (ID 961c63423f38d2c0) 
Start acquisition on digitizer VX1740D_34
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Acquisition complete - shutting down.
Acquisition ran for 15 seconds.
Collecting 43513 events.
Resulting in a collection rate of 2.90087 kHz.

Setup 2 digitizer(s):
	VX1740D_34
	VX1740D_31
Starting run 00512 (ID a08f9fdc4350dd48) 
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 15 seconds.
Collecting 55043 events.
Resulting in a collection rate of 3.66953 kHz.

.... AND AGAIN

Setup 2 digitizer(s):
	VX1740D_34
	VX1740D_31
Starting run 00540 (ID 6f5cccd2c2d586fa) 
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 15 seconds.
Collecting 55101 events.
Resulting in a collection rate of 3.6734 kHz.

ERROR: Unable to open digitizer [VX1740D_2]
Setup 1 digitizer(s):
	VX1740D_34
Starting run 00541 (ID 71d33b6675382885) 
Start acquisition on digitizer VX1740D_34
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Acquisition complete - shutting down.
Acquisition ran for 15 seconds.
Collecting 43979 events.
Resulting in a collection rate of 2.93193 kHz.

Setup 2 digitizer(s):
	VX1740D_34
	VX1740D_31
Starting run 00542 (ID d3a0ccc6b73cb309) 
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 15 seconds.
Collecting 54867 events.
Resulting in a collection rate of 3.6578 kHz.

Then again both digit failed, it run from run 542 with both digit at 16:00 till 17:10 run 601-602 one digit failed as well then the 2nd digit failed at 19:20 run 669-670-671. (one run per 100 sec) This needed power cycle the crate. 

ERROR: Unable to open digitizer [VX1740D_1]
ERROR: Unable to open digitizer [VX1740D_2]
Setup 0 digitizer(s):
Starting run 01027 (ID 3b2494047fdc2b86)
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Acquisition complete - shutting down.
Acquisition ran for 100 seconds.
Collecting 0 events.
Resulting in a collection rate of 0 kHz.

ERROR: Unable to open digitizer [VX1740D_1]
ERROR: Unable to open digitizer [VX1740D_2]
Setup 0 digitizer(s):
Starting run 01028 (ID a318c95beb5b1107)
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Acquisition complete - shutting down.
Acquisition ran for 100.001 seconds.
Collecting 0 events.
Resulting in a collection rate of 0 kHz.

ERROR: Unable to open digitizer [VX1740D_1]
ERROR: Unable to open digitizer [VX1740D_2]
Setup 0 digitizer(s):
Starting run 01029 (ID 20375ac89de1b1ae)
Running acquisition loop - Ctrl-C to interrupt
^CCaught interrupt - stop acquisition and clean up.
Acquisition complete - shutting down.
Acquisition ran for 84.772 seconds.
Collecting 0 events.
Resulting in a collection rate of 0 kHz.

**Comment by francescopis13** [comment]
And once I needed to power cycle the crate to make the digitiser alive again.

**Comment by francescopis13** [comment]
It is always the VX1740D_2 ( VX1740D_31) that fails

**Comment by francescopiscitelli** [comment]
Stopped both digit died at 19.00 (24-07-2018). I now included a 0.5s sleep between a stop and the start of a new run in the script, runs are 100s. Restarted at 9.45 (25-07-2018) after power cycle run 01032 all fine until 12.50 when run 01143 one digit failed again. But then next run 01144 is back to life. (Run 01227 and 01160 and 01175 and 01227 and 01230 and 01232 same thing happened). I stopped at run 01236. Then I increased all thresholds by 50 units to see if it is a problem of trigger it starts at 01237 but run 01240 failed again. And failed on digit 31: run 01857 and 01862. 

Setup 2 digitizer(s):
        VX1740D_34
        VX1740D_31
Starting run 01226 (ID f65e7756d85ac57b)
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 100 seconds.
Collecting 359986 events.
Resulting in a collection rate of 3.59986 kHz.

ERROR: Unable to open digitizer [VX1740D_2]
Setup 1 digitizer(s):
        VX1740D_34
Starting run 01227 (ID c5e67e525147693a) 
Start acquisition on digitizer VX1740D_34
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Acquisition complete - shutting down.
Acquisition ran for 100 seconds.
Collecting 285145 events.
Resulting in a collection rate of 2.85145 kHz.

Setup 2 digitizer(s):
        VX1740D_34
        VX1740D_31
Starting run 01228 (ID 19f9de7726bc129a) 
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt

**Comment by francescopiscitelli** [comment]
After talking to Hanno, he mentioned that this can be a hardware issue that we do not edit enough after a critical setting of the digitiser. I added a sleep of 0.5s before lunching jadaq in my script, but it does not change much. Troels, try to add a sleep somewhere when you for example set the configuration of the digitisers if there is something critical that need time in the hardware. And run it for example for a night every minute or so.

**Comment by tblum** [comment]
Checking the Boardready and PLLready flags did not help with this problem.

**Comment by hperrey** [comment]
Since waiting for the PLL-ready as implemented by @tblum apparently was not enough, here some thoughts for further investigations (that we can also discuss tomorrow in person):

- do the digitizers fail in any particular order? I.e. always `VX1740D_2` first, then the other? Or is it random? If not, it could be related to the way they are chained.
- what exactly is the fail state? Do we e.g. have pictures of the LEDs on the digitizers when they have failed? Or of the crate controller (if applicable)
- if we connect a different PC e.g. via USB to a failed digitizer, can we establish a connection then? (I guess not)
- is the data of the run prior to a failure ok? Is all the data there? If so, the digitizer must have ended up "broken" when closing it or when trying to open it again next run.
- is the issue data-rate dependent?
- is the issue with the link or with the state of the digitizer itself? I.e. does power cycling the attached computer help or do we need to power cycle the crate?
- is the failure rate linked to the number of times we open/close the connection (or perform the configuration) or the total run time alone? Can we provoke the failure quicker by having many very, very short runs or is it more likely to end up in a failed state after a long run?
- do we have similar tests using the other PC+crate and maybe a pulse generator?

@francescopis13 do you have any more insights into this issue already?
