### ISSUE TITLE
Detecting false clock reset is causing problems with HDF5 file writing

### ISSUE THREAD

**Issue by francescopiscitelli** [tblum/jadaq#12]
Data with ID Starting run 00457 is in /data/test23FP_nightwithscript/
Config file is in .../jadaq/config/config2digit_STF_FP2307.ini or here [config2digit_STF_FP2307.ini.txt](https://github.com/ess-dmsc/jadaq/files/2223932/config2digit_STF_FP2307.ini.txt)
The file is written anyhow but sometimes it is impossible to open it
HV on detector 1300V with Co-60 source
It seems a problem of higher rate, with larger number of triggers it happens more often 

MESSAGE:
acq 1
Setup 2 digitizer(s):
VX1740D_34
VX1740D_31
Starting run 00457 (ID dc04a3b9af741503)
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:
#000: ../../src/H5D.c line 170 in H5Dcreate2(): unable to create dataset
major: Dataset
minor: Unable to initialize object
#1: ../../src/H5Dint.c line 439 in H5D__create_named(): unable to create and link to dataset
major: Dataset
minor: Unable to initialize object
#2: ../../src/H5L.c line 1638 in H5L_link_object(): unable to create new link to object
major: Links
minor: Unable to initialize object
#3: ../../src/H5L.c line 1882 in H5L_create_real(): can't insert link
major: Symbol table
minor: Unable to insert object
#4: ../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
major: Symbol table
minor: Object not found
#5: ../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
major: Symbol table
minor: Callback failed
#6: ../../src/H5L.c line 1674 in H5L_link_cb(): name already exists
major: Symbol table
minor: Object already exists
Error while writing to HDF5 file: H5Dcreate2 failed
HDF5::write( 31, 1532438558258, 15 )
17 5116 334
7 6199 441
19 132468 285
11 163654 497
11 409553 314
16 437030 513
17 443187 250
28 585101 242
6 662726 602
9 860985 575
22 890774 256
19 896039 278
27 1117109 524
16 1210961 169
53 237663 610
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 100 seconds.
Collecting 368413 events.
Resulting in a collection rate of 3.68413 kHz.
acq 2
Setup 2 digitizer(s):
VX1740D_34
VX1740D_31
Starting run 00458 (ID 4bec1e7ab019b3e3)
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 100 seconds.
Collecting 369142 events.
Resulting in a collection rate of 3.69142 kHz.

**Comment by francescopiscitelli** [comment]
#004: ../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: ../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: ../../src/H5L.c line 1674 in H5L_link_cb(): name already exists
    major: Symbol table
    minor: Object already exists
Error while writing to HDF5 file: H5Dcreate2 failed
         HDF5::write( 31, 1532437214405, 18 )
       6       260933     274
      11       289930     307
      50       289942    1032
      51       289952     677
      31       326244    1361
      43       326257    1045
      15       343135     440
      23       438336     363
      22       438346     159
       9       572723     438
       5       622515     231
      21       893118     376
      11      1055449     288
       8      1176379     313
      52      1176401     554
       5      1176381     356
      10      1176380     354
       7      1176386     265
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 100 seconds.
Collecting 367704 events.
Resulting in a collection rate of 3.67704 kHz.

**Comment by francescopiscitelli** [comment]
Running acquisition loop - Ctrl-C to interrupt
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:
  #000: ../../src/H5D.c line 170 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: ../../src/H5Dint.c line 439 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: ../../src/H5L.c line 1638 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: ../../src/H5L.c line 1882 in H5L_create_real(): can't insert link
    major: Symbol table
    minor: Unable to insert object
  #004: ../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: ../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: ../../src/H5L.c line 1674 in H5L_link_cb(): name already exists
    major: Symbol table
    minor: Object already exists
Error while writing to HDF5 file: H5Dcreate2 failed
         HDF5::write( 31, 1532437730674, 19 )
      18        30596     318
       6        97092     330
      48        97113     809
       7        97093     350
      10       223366     378
      15       321341     251
       5       388557     425
       7       416663     569

**Comment by francescopiscitelli** [comment]
It seems that this issue happens more often when the triggers arrive more often, so with higher rate. Run from 01865 to 01889 (then setup changed) happens more often because I have lower the thresholds to have more random noise recorded. Up to this error: 

      38      1239951    1985
      40      1239944    2332
      52      1239941    2808
      34      1239954    1730
      44      1239946    2189
      49      1239942    2693
      50      1239942    2522
      51      1239950    1632
      55      1239948    2227
      43      1246430    2189
      52      1246431    2168
      37      1246442    1699
      40      1246435    1797
      49      1246432    1945
      44      1246433    1995
      50      1246432    1894
      51      1246435    2020
      55      1246436    1976
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 10 seconds.
Collecting 1454639 events.
Resulting in a collection rate of 145.464 kHz.

Setup 2 digitizer(s):
        VX1740D_34
        VX1740D_31
Starting run 01883 (ID 3993e135a7a08daa)
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
ERROR: unexpected exception during acquisition: CAEN_DGTZ_CommError
terminate called after throwing an instance of 'caen::Error'
  what():  CAEN_DGTZ_CommError
./script.sh: line 4: 25532 Aborted                 (core dumped) /home/mb/jadaq/build/jadaq -t $Duration -H /home/mb/jadaq/config/config2digit_STF_FP2307.ini

ERROR: Unable to open digitizer [VX1740D_2]
Setup 1 digitizer(s):
        VX1740D_34
Starting run 01884 (ID f92771def99237c8) 
Start acquisition on digitizer VX1740D_34
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_34
Acquisition complete - shutting down.
Acquisition ran for 10 seconds.
Collecting 1115842 events.
Resulting in a collection rate of 111.584 kHz.

**Comment by francescopiscitelli** [comment]
With very low threshold (basically 0) triggers all the time and it does immediately:

Setup 2 digitizer(s):
        VX1740D_34
        VX1740D_31
Starting run 01912 (ID 6b4a2bb9a689839e) 
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
ERROR: unexpected exception during acquisition: CAEN_DGTZ_CommError
terminate called after throwing an instance of 'caen::Error'
  what():  CAEN_DGTZ_CommError
./script.sh: line 4: 25951 Aborted                 (core dumped) /home/mb/jadaq/build/jadaq -t $Duration -H /home/mb/jadaq/config/config2digit_STF_FP2307.ini

then 

ERROR: Unable to open digitizer [VX1740D_1]
Setup 1 digitizer(s):
        VX1740D_31
Starting run 01913 (ID 367c48509828535b) 
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt


the digitiser that has 0 threshold is dead (no.34) and crate needs power cycle to get the digitiser back to life.

**Comment by francescopiscitelli** [comment]
Instead of lowering threshold but increasing HV to get more events same thing, one digit dies due to rate. Needs power cycle. 

Setup 2 digitizer(s):
	VX1740D_34
	VX1740D_31
Starting run 01961 (ID 7bef225fccc72e21) 
Start acquisition on digitizer VX1740D_34
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:
  #000: ../../src/H5D.c line 170 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: ../../src/H5Dint.c line 439 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: ../../src/H5L.c line 1638 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: ../../src/H5L.c line 1882 in H5L_create_real(): can't insert link
    major: Symbol table
    minor: Unable to insert object
  #004: ../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: ../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: ../../src/H5L.c line 1674 in H5L_link_cb(): name already exists
    major: Symbol table
    minor: Object already exists
Error while writing to HDF5 file: H5Dcreate2 failed
	 HDF5::write( 31, 1532597522261, 404 )
      10         1345    5855
      37         1389     723
       0         1623     986
      11        17970     989
      40        17972    2767
      41        17977    2383
      16        24605    2086
      62        24627    1974
      17        24611     880
       9        36218     941
      12        37813    1534
      16        37806    1742
      43        37807    3088
      19        37811     749
      42        37816    2285
      44        37816    1987
      13        40604    4765
      42        40614    3749
      43        40650     328
       8        48010    1250
       5        64761     994
      13        67936     906
      11        82419    1348
      10        98822    1753
      24       103859     974
       4       141789    1731
       6       141801     812
      10       152106    1204
       6       153345    9862
      45       153362    2221
       5       153354    1295
      44       153371    1888
...

...
      31      1212420    1572
       7      1213415    1136
      18      1218230     895
      16      1218240     524
       8      1219697    2407
      44      1219697    4518
      43      1219715    2196
      31      1223091    2026
ERROR: unexpected exception during acquisition: CAEN_DGTZ_CommError
terminate called after throwing an instance of 'caen::Error'
  what():  CAEN_DGTZ_CommError
./script.sh: line 4: 28077 Aborted                 (core dumped) /home/mb/jadaq/build/jadaq -t $Duration -H /home/mb/jadaq/config/config2digit_STF_FP2307.ini

ERROR: Unable to open digitizer [VX1740D_1]
Setup 1 digitizer(s):
	VX1740D_31
Starting run 01962 (ID 8e25650d6dbb74b5) 
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 9.999 seconds.
Collecting 212711 events.
Resulting in a collection rate of 21.2732 kHz.

ERROR: Unable to open digitizer [VX1740D_1]
Setup 1 digitizer(s):
	VX1740D_31
Starting run 01963 (ID 9415ea15e43710c3) 
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
Time out - stop acquisition and clean up.
Stop acquisition on digitizer VX1740D_31
Acquisition complete - shutting down.
Acquisition ran for 10 seconds.
Collecting 213700 events.
Resulting in a collection rate of 21.37 kHz.

**Comment by tblum** [comment]
Of course setting the reset that low will cause problems. The reset needs to be significantly higher than the resolution of the global time stamp. The resolution of the global timestamp is 1ms in the current implementation. 
@francescopis13 What is HV

**Comment by tblum** [comment]
Fixed bug - some datapoints were mislables, causing problems. Moved to using Packet Tables in the process.
