### ISSUE TITLE
COMMENTS: 

### ISSUE THREAD

**Issue by francescopiscitelli** [tblum/jadaq#13]
1 The system runs with no physical reset (68sec reset) with no issues in writing the HDF5 file, I also tried 1sec reset and 20ms reset, all fine. 

2 Same number of events in the file if reset comes more often file is much bigger: same statistics and same run duration 8.8Mb with 68s reset (no reset), 23Mb with 20ms reset 

3 Mixed mode seems to work fine

**Comment by tblum** [comment]
Not a bug
