### ISSUE TITLE
unrecognised option '--split'

### ISSUE THREAD

**Issue by fmessi** [tblum/jadaq#27]
testing _commit bbf37df89289a2574f26c65872e376afd33cab9e_ running the _runscript.sh_ 
It seems that the **--split** option is not available any more... it was one of the initial requirement for JADAQ and it is needed for two major reasons: 
1. to avoid having big data-file on long acquisitions
2. to have a clear point in time in the data to group/reject them (automatic changing of the instrument set-up, loss/instability of beam, etc...)

It is definitely **a must** for the option of writing data on disk directly! 
Can be re-opted in?!

**Comment by mortenjc** [comment]
as far as I remember we implemented splitting in the EFU. There seem to be little point
in dumping data twice. But when dumping from the EFU we get the benefit to be able 
to later rerun the data offline and refine the algorithms.

**Comment by mortenjc** [comment]
but I actually don't remember removing the option. Feel free to re-introduce it.

**Comment by hperrey** [comment]
I don't remember an option to split files from within jadaq either. We could look into it, since it shouldn't be too hard to implement -- but since more sophisticated data handling is already handled by using the EFU we might just want to stick to that. Let's discuss it offline.

**Comment by mortenjc** [comment]
fixed
