### ISSUE TITLE
Stats not printed during acquisition

### ISSUE THREAD

**Issue by fmessi** [tblum/jadaq#28]
testing on _commit bbf37df89289a2574f26c65872e376afd33cab9e_
the statistic are printed all together at the end of the data acquisition and **not** with the rate they are requested... they are actually collected at the right moment, but displayed on the screen when the run ends.

**Comment by fmessi** [comment]
I actually remember this being an old issue... can't find here on GitHub neither know how it was solved...

**Comment by hperrey** [comment]
Hej @fmessi 
What were the exact options you ran jadaq with? I think the default value for when printing stats during acq. is set to a very high value.

**Comment by fmessi** [comment]
Problem solved: it happens by using the _runscrip.sh_ 
should we take those old scripts (and config-files) out of the repository?!
