### ISSUE TITLE
caen.hpp: filterBoardConfigurationSetMask() implemented but not used

### ISSUE THREAD

**Issue by hperrey** [tblum/jadaq#7]
The routine filterBoardConfigurationSetMask() is implemented for the 740 and 740DPP to ensure conforming with CAEN's specifications on the model-dependent board configuration but its use is commented out in setBoardConfiguration().

Is there any particular reason for that?

Applies e.g. to devel branch, commit 44adcb63.

**Comment by tblum** [comment]
No. Use it if you want. I just want freedom. 
Not a bug
